addons:
  apt:
    packages:
    - lib32z1
    - lib32stdc++6

language: c

sudo: false

script:
- if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then bash ci/test.sh; fi
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash ci/build.sh $TRAVIS_TAG; fi

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: MOmLu3Z5ztaMQ9dMaJxehiG+7gZQYNahQL6Z7VyA8Whd4G6II5t+X/UrgaTQxPYrWedDCP0WTDDDgGDXy5I5Ph1E4GzbJAaFYZxl7xuN5SOcf/jFkQpLRoxX0IIMXXo5huLHG/7pXyeLiWK70SRKlW88ceVsGGSNrUwoaguQWfrH5pGxXfsKAHm27N+K4JZLX8z7HqbyrQA+6fLrvJXeIkYwSN6Q3RhNw3YTQNp6g7TxUubFA9GAVjVf7kXNq0oV086PABWDj7drL6bnVdKkvquBsFcCwg4nHCrSdIjw9+osYJcVgsLEu0zn3YJUjiaCrnC9iB30aQmylq8WfdyX3l5DNpdAls1AIbCr6XU4Pcbnve0surVtSpfa4ULuH7Qt69E8KfwCtSB5eTak12YkXTTAPeA5wcGZIyinPSSBioS4FPxRNYsYYB+2dILVWFlU9uA6MN5U/g9KvPex/2TjHh5tuC0HhCrGhESXlRPXqrl8RNfktY/3S0RIayw6BcdNa8mVP2PZosjy4OHyEa/SjPg+cfi3jpaf5zELzyMz6EghAyn98ZwcZQ03ZJo6FAVFArdoW/L8Qhv8BjpmJKKntngQsc0w1NX0T+m0a2jldhdm287xBJXWyIJw7pKmzI3Vvij3RLg4eKUWnxigKGUPg/2Q3cIZJPZKXt3M6VbhFWI=
  file: StackHS.zip
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: Hexer10/StackHealthShot